### PR TITLE
Upgrade hive_crdt

### PR DESCRIPTION
**Pull request by agent3bood**
Related issue https://github.com/cachapa/tudo_client/issues/19

### CODE REVIEW

**Comment by cachapa** [comment]
Unfortunately it's not as trivial as simply upgrading the package version, otherwise I'd have done it myself (I'm the maintainer of both `crdt` and `hive_crdt`).

Performing this change would break the hive stores in every device where the app is already in use, and migration isn't trivial.

**Comment by agent3bood** [comment]
Thanks for explaining, I wan un able to run the project (new install) with the old version, and I had to upgrade it.
Is it possible to migrate the local Hive db, I know that Hive does not support migrations by default, but still is the data migrate able?

**Comment by cachapa** [comment]
Sorry I missed this update.

To be honest I've been playing around with CRDTs in another project and am coming to the realization that Hive is the wrong backend for this use case since CRDTs grow monotonically, which makes Hive slower and more memory hungry over time.

I'm currently experimenting with sqlite as a backend, and it seems to work better. If I have the time, I'll publish a hive_sqlite package at some point.

**Comment by cachapa** [comment]
Closing this as the PR is now outdated

**Pull request closed without merging**
